image: alpelabs/ci-vi:latest

pipelines:
  default:
    - step:
        name: Build
        caches:
          - maven
          - docker
        script:
          - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/build.sh)
        services:
          - docker
  branches:
    develop:
      - step:
          name: Build
          caches:
            - maven
            - docker
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/build.sh)
          services:
            - docker
      - step:
          name: Deploy to DEV
          deployment: test
          trigger: automatic
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/deploy.sh)
    release/*:
      - step:
          name: Build
          caches:
            - maven
            - docker
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/build.sh)
          services:
            - docker
      - step:
          name: Deploy to UAT
          deployment: staging
          trigger: automatic
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/deploy.sh)
    hotfix/*:
      - step:
          name: Build
          caches:
            - maven
            - docker
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/build.sh)
          services:
            - docker
      - step:
          name: Deploy to FIX
          deployment: staging
          trigger: automatic
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/deploy.sh)
    master:
      - step:
          name: Build
          caches:
            - maven
            - docker
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/build.sh)
          services:
            - docker
      - step:
          name: Deploy to PRD
          deployment: production
          trigger: manual
          script:
            - bash <(curl -s https://bitbucket.org/timefinanceiro/maven-resources/raw/master/src/main/resources/deploy.sh)

definitions:
  services:
    docker:
      memory: 2048